### ISSUE TITLE
follow user functionality

### ISSUE THREAD

**Issue by HomeboxJim** [ng-nj/ng-nj.org#14]
implement functionality for following other users

**Comment by JimTheMan** [comment]
Ok, first of all we're going to need to update our "schema" for what a user object looks like in the firebase database. 

the user object should now have two more properties:

- following: this is a list node that contains user objects and represents the list of other users that this user is following.

- followers: this is a list node that contains user objects and represents the list other other users that are following this user. 


So as usual we have the html part to this and the Javascript part. 

In the HTML template what changes do we need to make? When the follow button is clicked,
