### ISSUE TITLE
Title on Home Page is Incorrect!

### ISSUE THREAD

**Issue by JimTheMan** [ng-nj/ng-nj.org#2]
This is so bad that it's laughable. I know it's my fault because I'm the only developer who worked on this, and I remember just making random changes just so that I could check that the CI was was working. Well yes, it is working. Except there's not tests in place to prevent from pushing bugs live. Lol. Then I was able to hook up a godaddy domain name ng-nj.com (although I really wanted ng-nj.org, but they baited me into ng-nj.com for $1 for a year so I'm testing hosting with gh-pages but using a custom domain name ng-nj.com). Yes, this bug is live right now at <a href='http://www.ng-nj.com'>www.ng-nj.com</a>! 

What the kind of website has a title like that. Really Jim.

I didn't realize this until I went to a javascript meetup yesterday and showed it to a bunch of people. hehe. Anyway, I'm just talking to myself right now. So please, go fix that. But even better, write tests to make sure something like this doesn't happen again! It should say, _Welcome to NG-NJ_ and not _GL Welcome to_ NG-NJ!!_

smh...

![ngnjorg](https://cloud.githubusercontent.com/assets/5354163/18817870/612eb444-8339-11e6-91ae-0131a022caf9.png)

Please fix this. 

Also, the other firebase stuff. I'll make other issues for that, but this should be a quick fix. 

Dev Jim: But wait, we need somehow integrate protractor in order to really write the necessary tests to have full coverage.

pm Jim: Dude, just change the source code and write a unit test for it. How do you "not know" how to do protractor on travis ci. That is a big deal man.

dev jim: I know, but when I just threw it up on travis it was giving me errors that it can't find the browser window. I guess we should use sauce labs or browserstack, but they are expensive... And I haven't integrated them into CI before so idk how long it will take, if it will work with our current versions of all our npm packages, etc.

pm jim: Dude, just take your credit card and put it into sauce labs. You can make it work if you really try. Pay someone to get you set up with a working environment if you have to. But can you just change it the source code first please. Lol :)

div jim: ok fine. Change in the source code is done.

pm jim: phew. ok thanks. Can you push it live now?

dev jim: hold on. there are some failing tests. 

pm jim: 0_0

dev jim: jk

![troll-face](https://cloud.githubusercontent.com/assets/5354163/18817937/bfb447ee-833a-11e6-9c70-57105e2cfd75.png)

**Comment by HomeboxJim** [comment]
All good now
